language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  on:
    branch: master
  app: easyadminsystem
  api_key:
    secure: L61o940Cw4S6iQ5TCglzKjcaAqC+oillKCQXWUCNAxNCF5s++dVMod6VYtWqsJUD1mRxBczC9QGfwTDlLr1/hQhcx78mh3XoCWmnJMQEynGodilT67WOdIeSKpXBzR5zSyAy0wmrQPndcDiQ1oZ+XIvp0tPoI099OspYP6zTIkOvgodZWmOztx+Xmod4H4elxD34e5aNbBMTpuFJtjcvB5oKXBjjEJAw7u7LOnYT41F3acGU2/6/Pu51du8QLloDuksay5DJLOTu2A7vllEBW0Wk6/JppIobME6ih6mTeE0WJ9YgxQOX+ZaPoUACQe/KmUzaaQhKmw6btx4M9LR/cWh/hJwECQ2GKlrNk1ywJjTPGAAaFNGXirPUDQ2mo/raS5wsXXvdKehFKyExLuYmau0ucI7euVqRMtnjd2reDO7D0qZyjeaTh3A+iNGhRxp3Z8aLHQPK/p8+3bBlLetS0OOKNKEr4MGa0emT3fT+j5Yf+etrXJtQcPy8lq7cy6ZOJdBsBkXfHxIpQOpFlgWSPubWyloumKKx/B5IQQaI91dkiMW5Mho68H8/EpFgUnsJlVbuRy/QStODrM44p3SgQJoYCnCg60EwdrGXbmMswrpd80e+NM0KrR92flKEXeJLLXCbPyXo66MvSqKPibr8Vh+75ofkoBI3bCBKknCcisU=
  skip_cleanup: true
